# Generated by Django 2.2 on 2021-03-23 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('short_description', models.CharField(blank=True, max_length=512, null=True, verbose_name='Short description')),
                ('source_title', models.CharField(blank=True, max_length=512, null=True, verbose_name='Source title')),
                ('source_link', models.TextField(blank=True, null=True, verbose_name='Source link')),
                ('slug', models.SlugField(allow_unicode=True, max_length=512, verbose_name='Slug')),
                ('keywords', models.TextField(verbose_name='Keywords')),
                ('meta_title', models.TextField(verbose_name='Meta title')),
                ('meta_description', models.TextField(verbose_name='Meta description')),
                ('canonical_tag', models.TextField(verbose_name='Canonical tag')),
                ('content', models.TextField(verbose_name='Content')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('image', models.ImageField(upload_to='blog_image', verbose_name='Blog image')),
                ('thumbnail', models.ImageField(upload_to='blog_image_thumbnail', verbose_name='Thumbnail')),
                ('description', models.CharField(max_length=256, verbose_name='Description')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('content_type', models.CharField(choices=[('file', 'file'), ('text', 'text')], max_length=128, verbose_name='Content type')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog', verbose_name='File')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file.File', verbose_name='File')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.BlogImage', verbose_name='Banner image'),
        ),
    ]
