# Generated by Django 2.2 on 2021-05-05 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='Is draft'),
        ),
        migrations.AlterField(
            model_name='contentlist',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents_list', to='blog.Blog', verbose_name='Blog'),
        ),
    ]
