# Generated by Django 2.2 on 2021-03-23 21:00

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=512, verbose_name='Slug')),
                ('image', models.ImageField(upload_to='category', verbose_name='Image')),
                ('short_description', models.CharField(blank=True, max_length=512, null=True, verbose_name='Short description')),
                ('color', models.CharField(blank=True, max_length=128, null=True, verbose_name='Color')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.Category', verbose_name='Parent category')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
