# Generated by Django 2.2 on 2021-05-20 22:54

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20210502_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('language', models.CharField(max_length=64, verbose_name='Language')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=512, verbose_name='Slug')),
                ('short_description', models.CharField(blank=True, max_length=512, null=True, verbose_name='Short description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category', verbose_name='Category')),
            ],
            options={
                'unique_together': {('language', 'category')},
            },
        ),
    ]
