# Generated by Django 2.2 on 2021-05-20 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20210520_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytranslation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='category.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='language',
            field=models.CharField(choices=[('EN', 'EN'), ('DE', 'DE'), ('FR', 'FR')], max_length=64, verbose_name='Language'),
        ),
    ]
